language: go
go:
- 1.15.x
services:
- docker
script:
- make bootstrap
- make test
notifications:
  slack:
    rooms:
      secure: oMF1YiLMuHEtuQaodOchinff77bR3y50V1ax2Fj8VwrGHwOVQTfOd5ArWBugnzhvmpe0JVeS3nq29Qydja7SWz70s/1u5XVjlLHaO9nG0o2eBXA5GafGG6R1ZPYx6xpjMvFJZUH97u2TXqufdKQeR34qiWqvKdxiNQXEK3bj0d4BjIdWEpbOqce6cy/q1/QBZ7WpzZOe66mutQzyG5BjKRAHF2bVPom1YKvOIZtkfwWzWSiDIreRZetWnrknO9hmXFSq1oYmqY07flUAlWQKnNWGVTfcbPacvR7hyEOwaNZ0jbbY6YaZDJvZoXUbH2e1jhAU8oU88KmKLIeSYU4BXDMfcpz1Mhh21rcZ7FfaKmMim31LRcgC4MNMtW3DPyi3nesErxbrMI2DUwzu66iRq/YuESGO4bhrzhO+0lRvnnq84qQbf5EmwL1eX3bGkunZ0JkpOJ9+MBbBsrtS++58NIrHxIOfymaGqTU25Ul6XRcqHlA0eDR43Skbkqu2wgljGx5dv2e3WpP9Uk9nsC0dAlYt+FcUNu5Cxk8HdyHrxgz8UobSylvjCaT1Rl39jLtWhJQaR+LaQH+qprbl81YskCvTJyDHinLfLZmDoBpgaIW/mZfLZUlaYzKGyBvXTnn9YfdiK9ahdgDXjyrYVNPkMssK/uZdBYzhg10MMpiNzDQ=
after_success:
  - bash <(curl -s https://codecov.io/bash)
